package dev.safi.restaurant_management_system.enums;

public enum FeatureName {
    DINE_IN,
    TAKEAWAY,
    DELIVERY,
    QR_ORDERING,
    ONLINE_PAYMENT,
    TABLE_RESERVATION,
    LOYALTY_PROGRAM,
    INVENTORY_MANAGEMENT,
    KITCHEN_DISPLAY,
    ANALYTICS,
    MULTI_BRANCH,
    STAFF_MANAGEMENT,
    CUSTOMER_APP,
    WAITER_APP,
    DELIVERY_APP,
    LIVE_ORDER_DISPLAY,
    WAITING_GAMES,
    DISCOUNT_COUPONS,
    REVIEW_RATINGS
}
